name: "Lite Jira Update Action"
description: "A GitHub Action to post a comment to a Jira issue."
author: "Ujjval Rajput"
inputs: {}
runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "message-circle"
  color: "blue"
