# GitHub Actions Workflow: Trigger Jira Comment on PR Merge

# This workflow triggers when a pull request is closed.
# The script will only post to Jira if the PR was actually merged.
on:
  pull_request:
    types: [closed]  # Only trigger when a PR is closed (merged or not)

permissions:
  contents: read
  pull-requests: read

jobs:
  post-jira-comment:
    name: Post comment to Jira
    runs-on: ubuntu-latest  # Use GitHub's hosted Linux runner

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4  # Pulls in the repo code

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use Node.js 20 runtime

      - name: Install dependencies
        run: npm ci  # Clean install from package-lock.json

      - name: Run Lite Jira Update Action
        uses: ./  # Run the local custom action defined in action.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Inject GitHub token that GitHub Actions provides
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}  # Inject Jira token securely from GitHub Secrets
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}  # Inject Jira domain the same way
